version: 1.0
type: port
name: admin
spec:
  port: 8080
  acceptors: 1
  apps:
    admin_api:
      ws: "/ws"
      http: "/api"
    upload:
      http: "/files"
    admin_ui:
      http: "/scm/app.scm"
