{application,cmqueue,
             [{description,"An OTP application"},
              {vsn,"0.1.0"},
              {registered,[]},
              {mod,{cmqueue_app,[]}},
              {applications,[kernel,stdlib,cmconfig,cmdb]},
              {env,[]},
              {modules,[cmqueue,cmqueue_app,cmqueue_sup,cmqueue_worker]},
              {maintainers,[]},
              {licenses,["Apache 2.0"]},
              {links,[]}]}.
