version: 2
jobs:
  build:
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - checkout
      - docker build -t pedrogutierrez/cmnode:latest .
      - docker push pedrogutierrez/cmnode:latest
