version: 2
jobs:
  build:
    docker:
      - image: docker:18.06.1-ce-git
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Build application Docker image
          command: |
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker build -t pedrogutierrez/cmnode:latest .
            docker push pedrogutierrez/cmnode:latest
