version: 1.0
type: module
category: client
name: account_ui 
spec:
  init:
    model:
      message:
        text:
          literal: ""
      email: 
        text:
          literal: ""
      password:
        text:
          literal: ""
      password_confirm:
        text:
          literal: ""
      first:
        text:
          literal: ""
      last:
        text:
          literal: ""
      state: 
        keyword: login 
    cmds:
      - effect: ui 
        encoder: login_view
  update:
    ws_connected:
      model:
        message:
          text:
            literal: "Server reachable"
      cmds:
        - effect: ui
          encoder: login_view
    ws_disconnected:
      model:
        message:
          text:
            literal: "Disconnected from server" 
      cmds:
        - effect: ui
          encoder: login_view
    ws_error:
      model:
        message:
          text:
            literal: "Server connection error"
      cmds:
        - effect: ui
          encoder: login_view
    ws_pong:
      model:
        pong:
          text:
            literal: ""
    email_changed:
      model:
        email:
          key: value
      cmds:
        - effect: ui
    password_changed:
      model:
        password:
          key: value
      cmds:
        - effect: ui
    first_changed:
      model:
        first:
          key: value
      cmds:
        - effect: ui
    last_changed:
      model:
        last:
          key: value
      cmds:
        - effect: ui
    password_confirm_changed:
      model:
        password_confirm:
          key: value
      cmds:
        - effect: ui
    send_login:
      model:
        state: 
          keyword: logging_in
      cmds:
        - effect: ws
          encoder: login
        - effect: ui
    send_signup:
      model:
        state:
          keyword: registering
      cmds:
        - effect: ws
          encoder: signup 
    recover_password:
      cmds:
        - effect: ws
          encoder: recover_password 
    show_recover_password:
      cmds:
        - effect: ui
          encoder: recover_password_view
    show_signup:
      cmds:
        - effect: ui
          encoder: signup_view
    show_login:
      cmds:
        - effect: ui
          encoder: login_view
    user:
      - when:
          eq:
            - key: state
            - keyword: registering
        model:
          password:
            text: 
              literal: ""
          password_confirm:
            text: 
              literal: ""
          message:
            text:
              literal: "Now please login with your new account"
        cmds:
          - effect: ui
            encoder: login_view
      - when:
          eq:
            - key: state
            - keyword: logging_in 
        model:
          message:
            text:
              literal: ""
        cmds:
          - effect: events
            encoder: user_logged_in
    invalid:
      - when:
          eq:
            - key: state
            - keyword: logging_in
        model: 
          state: 
            keyword: login
          message:
            text:
              literal: "Please check your data and try again"
        cmds:
          - effect: ui
    not_found:
      - when:
          eq:
            - key: state
              keyword: logging_in
        model: 
          state: 
            keyword: login
          message:
            text:
              literal: "Invalid credentials"
        cmds:
          - effect: ui
            encoder: login_view
    forbidden:
      - when:
          eq:
            - key: state
            - keyword: logging_in
        model: 
          state: 
            keyword: login
          message:
            text:
              literal: "Invalid credentials"
        cmds:
          - effect: ui
  encoders:
    login:
      object:
        action:
          text:
            literal: "login"
        username: 
          key: email 
        password:
          key: password
    signup:
      object:
        action:
          text: 
            literal: "register"
        username:
          key: email 
        password:
          key: password
        password_confirm:
          key: password_confirm
        first:
          key: first
        last: 
          key: last
    recover_password:
      object:
        username: 
          key: email 
    user_message:
      view:
        tag: div
        attrs: 
          key: user-message
          class: warning
        children:
          - text: 
              key: message 
    label:
      view:
        tag: label
        attrs:
          class: "form-label"
        children:
          - text: 
              key: title
    textarea:
      view:
        tag: div
        attrs:
          key: 
            key: id
          class: "form-group"
        children:
          - tag: label
            attrs:
              class: "form-label"
              for: 
                key: id
            children:
              - text: 
                  key: title
          - tag: textarea
            attrs:
              class: "form-input"
              type: "text"
              id: 
                key: id
              placeholder: 
                key: title
              onchange:
                key: id
              value:
                key: value
              rows:
                key: rows
    input:
      view:
        tag: div
        attrs:
          key: 
            key: id
          class: "form-group"
        children:
          - tag: label
            attrs:
              class: "form-label"
              for: 
                key: id
            children:
              - text: 
                  key: title
          - tag: input
            attrs:
              class: "form-input"
              type: "text"
              id: 
                key: id
              placeholder: 
                key: title
              onchange:
                key: id
              value:
                key: value
    password:
      view:
        tag: div
        attrs:
          key: 
            key: id
          class: "form-group"
        children:
          - tag: label
            attrs:
              class: "form-label"
              for: 
                key: id
            children:
              - text: 
                  key: title
          - tag: input
            attrs:
              class: "form-input"
              type: "password"
              id: 
                key: id
              placeholder: 
                key: title
              onchange:
                key: id
              value:
                key: value

    button:
      view:
        tag: div
        children:
          - tag: button
            attrs:
              class: "btn btn-primary"
              onclick:
                key: click
            children:
              - text:
                  key: title
    link:
      view:
        tag: div
        attrs:
          onclick:
            key: click
          key: 
            key: id
        children:
          - tag: a
            attrs:
              href: "#"
            children:
              - text: 
                  key: title
    login_view:
      view:
        tag: div 
        attrs:
          class: container
        children:
          - tag: h1
            attrs:
              key: title
            children:
              - text: "Welcome"
          - view: user_message
            params:
              object:
                message:
                  key: message
            when:
              is_set:
                key: message
          - view: input
            params:
              object:
                id: 
                  literal: "email"
                title:
                  literal: "Email"
                value:
                  key: email
          - view: password 
            params:
              object:
                id: 
                  literal: "password"
                title:
                  literal: "Password"
                value:
                  key: password
          - view: button
            params:
              object:
                click:
                  keyword: send_login
                title:
                  literal: "Login"
          - view: link
            params:
              object:
                id: 
                  literal: recover_password 
                click:
                  keyword: show_recover_password
                title:
                  literal: "Recover password"
          - view: link
            params:
              object:
                id: 
                  literal: signup
                click:
                  keyword: show_signup
                title:
                  literal: "Create an account"
    signup_view:
      view:
        tag: div
        attrs:
         class: container
        children:
          - tag: h1
            attrs:
              key: title
            children:
              - text: "Create an account"
          - view: user_message
            params:
              object:
                message:
                  key: message
          - view: input
            params:
              object:
                id: 
                  literal: "first"
                title:
                  literal: "First name"
                value:
                  key: first
          - view: input
            params:
              object:
                id: 
                  literal: "last"
                title:
                  literal: "Last name"
                value:
                  key: last
          - view: input
            params:
              object:
                id: 
                  literal: "email"
                title:
                  literal: "Email"
                value:
                  key: email
          - view: password 
            params:
              object:
                id: 
                  literal: "password"
                title:
                  literal: "Password"
                value:
                  key: password
          - view: password 
            params:
              object:
                id:
                  literal: "password_confirm"
                title:
                  literal: "Password (again)"
                value:
                  key: password_confirm
          - view: button
            params:
              object:
                click:
                  keyword: send_signup
                title:
                  literal: "Signup"
          - view: link
            params:
              object:
                id: 
                  literal: recover_password 
                click:
                  keyword: show_recover_password
                title:
                  literal: "Recover password"
          - view: link
            params:
              object:
                id: 
                  literal: signin
                click:
                  keyword: show_login
                title:
                  literal: "Login"
    recover_password_view:
      view:
        tag: div 
        attrs:
          class: container
        children:
          - tag: h1
            attrs:
              key: title
            children:
              - text: "Recover password"
          - view: user_message
            params:
              object:
                message:
                  key: message
          - view: input
            params:
              object:
                id: 
                  literal: "email"
                title:
                  literal: "Email"
                value:
                  key: email
          - view: button
            params:
              object:
                click:
                  keyword: recover_password
                title:
                  literal: "Recover password"
          - view: link
            params:
              object:
                id: 
                  literal: signin
                click:
                  keyword: show_login
                title:
                  literal: "Login"
          - view: link
            params:
              object:
                id: 
                  literal: signup
                click:
                  keyword: show_signup
                title:
                  literal: "Create an account"
    user_logged_in:
      object:
        event: 
          keyword: user_logged_in
  decoders:
    ws_connected:
      object:
        effect:
          keyword: ws
        event:
          keyword: connected
    ws_disconnected:
      object:
        effect:
          keyword: ws
        event:
          keyword: disconnected
    ws_error:
      object:
        effect:
          keyword: ws
        event:
          keyword: error
    ws_pong:
      object:
        effect:
          keyword: ws
        data:
          object:
            action:
              text:
                literal: "pong"
    show_login:
      object:
        effect:
          keyword: ui
        event:
          keyword: show_login
    show_signup:
      object:
        effect:
          keyword: ui
        event:
          keyword: show_signup
    show_recover_password:
      object:
        effect:
          keyword: ui
        event:
          keyword: show_recover_password
    email_changed:
      object:
        effect:
          keyword: ui
        event:
          text:
            literal: email
        value:
          text: any
    password_changed:
      object:
        effect:
          keyword: ui
        event:
          text:
            literal: password
        value:
          text: any
    first_changed:
      object:
        effect:
          keyword: ui
        event:
          text:
            literal: first 
        value:
          text: any
    last_changed:
      object:
        effect:
          keyword: ui
        event:
          text:
            literal: last
        value:
          text: any
    password_confirm_changed:
      object:
        effect:
          keyword: ui
        event:
          text:
            literal: password_confirm 
        value:
          text: any
    send_login:
      object:     
        effect:
          keyword: ui
        event:
          keyword: send_login
    send_signup:
      object:     
        effect:
          keyword: ui
        event:
          keyword: send_signup
    recover_password:
      object:     
        effect:
          keyword: ui
        event:
          keyword: recover_password
    user:
      object:
        effect:
          keyword: ws
        data:
          object:
            id:
              text: any
            email:
              text: any
            first: 
              text: any
            last:
              text: any
    invalid:
      object:
        effect: 
          keyword: ws
        data:
          object:
            error:
              text:
                literal: invalid
    not_found:
      object:
        effect: 
          keyword: ws
        data:
          object:
            error:
              text:
                literal: not_found
    forbidden:
      object:
        effect: 
          keyword: ws
        data:
          object:
            error:
              text:
                  literal: forbidden
  effects:
    events:
      type: elementary-events
    ui:
      type: elementary-ui
    ws:
      type: elementary-ws
      settings:
        secure:
          keyword: no 
        path:
          text:
            literal: "/ws"
        persistent: 
          keyword: true
        ping:
          object:
            action:
              keyword: ping
