version: 1.0
type: module
category: ui
name: admin_common_ui
spec:
  encoders:
    progress:
      view:
        tag: progress
        attrs:
          class: "progress"
          value:
            key: value
          max:
            key: max
    sidebar_icon:
      view:
        tag: div
        attrs:
          class: "sidebar-icon c-hand"
          onclick:
            key: name
          key: 
            key: name
        children:
          - tag: i
            attrs:
              class: 
                key: style
          - tag: div
            attrs:
              class: "mt-1"
            children:
              - text:
                  key: title
    layout:
      view:
        tag: div
        attrs:
          class: "off-canvas"
          key: "layout"
        children:
          - tag: div
            attrs:
              id: "sidebar"
              class: "off-canvas-sidebar active"
            children:
              - view:
                  key: sidebar
          - tag: div
            attrs:
              class: "admin-content off-canvas-content"
            children:
              - view: user_message
                params:
                  object:
                    message:
                      maybe:
                        key: message
              - view:
                  key: content_view
                params:
                  object:
                    data:
                      maybe:
                        key: contents
    main:
      view:
        tag: div
        attrs:
          key: 
            key: view 
        children:
          - tag: h2
            attrs:
              class: "content-view"
            children:
              - text:
                  key: title
          - view:
              key: view
            params:
              object:
                data:
                  maybe:
                    key: data

    section:
      view:
        tag: div
        attrs:
          key: 
            key: view 
        children:
          - tag: section
            attrs:
              class: "section-view"
            children:
              - view:
                  key: view
                params:
                  object:
                    data:
                      key: data
    table:
      view: 
        tag: div
        attrs:
          class: "table-view"
        children:
          - tag: table
            children:
              - tag: thead
                children:
                  loop:
                    key: headers
                  with: table_header
              - tag: tbody
                children:
                  loop:
                    key: items
                  context:
                    maybe:
                      key: context
                  with:
                    key: item_view

    table_header:
      view:
        tag: th
        children:
          - text:
              key: title
              in: item
    text_view:
      view:
        tag: span
        children:
          - text:
              key: data
    info_item_view:
      view:
        tag: div
        attrs:
          class: "columns col-12 mt-2"
        children:
          - tag: div
            attrs:
              class: "col-6"
            children:
              - tag: strong
                children:
                  - text:
                      key: title
                      in: item
          - tag: div
            attrs:
              class: "col-6"
            children:
              - tag: div
                children:
                  - view:
                      key: view
                      in: item
                    params:
                      object:
                        data:
                          key: value
                          in: item
    properties_view:
      view:
        tag: div
        attrs:
          class: "columns"
        children:
          loop:
            key: items
          with: info_item_view
    info_view:
      view:
        tag: div
        attrs:
          class: "section-view"
        children:
          - tag: h4
            children:
              - text:
                  key: title
          - tag: div
            attrs:
              key: "info"
              class: "card"
            children:
              - tag: div
                attrs:
                  class: "card-body columns"
                children:
                  loop:
                    key: items
                  with: info_item_view
    json_view:
      view:
        tag: pre
        attrs:
          class: "code"
          data-lang: "json"
        children:
          - tag: code
            children:
              - json:
                  key: source
