version: 1.0
type: module
category: ui
name: admin_common_ui
spec:
  encoders:
    sidebar_icon:
      view:
        tag: div
        attrs:
          class: "sidebar-icon c-hand"
          onclick:
            key: name
          key: 
            key: name
        children:
          - tag: i
            attrs:
              class: 
                key: style
          - tag: div
            attrs:
              class: "mt-1"
            children:
              - text:
                  key: title
    layout:
      view:
        tag: div
        attrs:
          class: "off-canvas"
          key: "layout"
        children:
          - tag: div
            attrs:
              id: "sidebar"
              class: "off-canvas-sidebar active"
            children:
              - view:
                  key: sidebar
          - tag: div
            attrs:
              class: "off-canvas-content"
            children:
              - view: user_message
                params:
                  object:
                    message:
                      maybe:
                        key: message
              - view:
                  key: content_view
                params:
                  object:
                    data:
                      maybe:
                        key: contents
    main:
      view:
        tag: div
        attrs:
          key: 
            key: view 
        children:
          - tag: h2
            attrs:
              class: "content-view"
            children:
              - text:
                  key: title
          - view:
              key: view
            params:
              object:
                data:
                  maybe:
                    key: data

    section:
      view:
        tag: div
        attrs:
          key: 
            key: view 
        children:
          - tag: section
            attrs:
              class: "section-view"
            children:
              - view:
                  key: view
                params:
                  object:
                    data:
                      key: data
    table:
      view: 
        tag: div
        attrs:
          class: "table-view"
        children:
          - tag: table
            children:
              - tag: thead
                children:
                  loop:
                    key: headers
                  with: table_header
              - tag: tbody
                children:
                  loop:
                    key: items
                  with:
                    key: item_view

    table_header:
      view:
        tag: th
        children:
          - text:
              key: title
              in: item
