version: 1.0
type: module
category: client
name: admin_scm
priority: lowest
spec:
  init:
    model:
      scheme:
        text: 
          literal: "Hello" 
    cmds:
      - effect: scheme
        encoder: app
  update:
    scheme:
      model:
        scheme: 
          from: source 
      cmds:
        - effect: notify
          encoder: scheme
  encoders:
    app:
      object:
        app:
          spec: 
            modules:
              - account_ui
              - admin_common_ui
              - apps_ui
              - nodes_ui
              - ports_ui
              - buckets_ui
              - app_ui
              - module_ui
    scheme:
      data: 
        from: scheme
  decoders:
    scheme:
      object:
        language:
          keyword: scheme
        status:
          keyword: ok
        source:
          text: any
