version: 1.0
type: module
category: ui
name: app_ui
spec:
  init:
    model:
      category: 
        keyword: none
      debug:
        keyword: none
      config:
        list: []
  update:
    app_info:
      model:
        category:
          key: category
          in: 
            key: info
            in: data
        debug:
          key: debug
          at:
            key: info
            in: data
      cmds:
        - effect: ui
          encoder: app_view
    app_config:
      model:
        config:
          key: config
          in: data
      cmds:
        - effect: ui
          encoder: app_view
    no_modules:
      cmds:
        - effect: ui
          encoder: app_view
    modules:
      model:
        modules:
          key: modules
          in: data
        modules_view:
          keyword: app_modules_table_view
      cmds:
        - effect: ui
          encoder: app_view
    show_app:
      model:
        modules:
          list: []
        app:
          key: name
          in:
            key: app
            in: event
        modules_view: 
          keyword: app_modules_empty_view
      cmds:
        - effect: ui
          encoder: app_view
        - effect: ws
          encoder: app_modules
        - effect: ws
          encoder: app_info
        - effect: ws
          encoder: app_config
  encoders:
    app_modules:
      object: 
        action:
          keyword: modules
        app:
          key: app
    app_info:
      object: 
        action:
          keyword: info
        app:
          key: app
    app_config:
      object: 
        action:
          keyword: config
        app:
          key: app
    module_selection:
      object:
        name:
          keyword: show_module
        module:
          key: item 
    app_modules_empty_view:
      view:
        tag: 'div'
        children:
          - text:
              literal: "No modules found"
    app_module_table_item_view:
      view:
        tag: "tr"
        attrs:
          key:
            key: name
            in: item
        children:
          - tag: td
            children:
              - tag: a
                attrs:
                  class: "c-hand"
                  onclick:
                    encoder: module_selection
                children:
                  - text:
                      key: name
                      in: item
    app_modules_table_view:
      view:
        view: table
        params:
          object:
            headers:
              list:
                - object:
                    title: 
                      text:
                        literal: "Name"
            items:
              key: modules
            item_view:
              keyword: app_module_table_item_view
    
    app_modules_section_view:
      view:
        tag: div
        children:
          - tag: h4
            children:
              - text: 
                  literal: "Modules"
          - view:
              key: modules_view
            params:
              object:
                modules:
                  key: modules

    app_setting_name_view:
      view:
        tag: div
        attrs:
          key: 
            key: key
            in: item
        children:
          - tag: strong
            children:
              - text:
                  key: key
                  in: item
    app_setting_value_view:
      view:
        tag: div
        attrs:
          key: 
            key: key
            in: item
        children:
          - text:
              key: value
              in: item
    app_settings_view:
      view:
        tag: div
        attrs:
          class: "section-view"
        children:
          - tag: h4
            children:
              - text:
                  literal: "Settings"
          - tag: div
            attrs:
              key: "info"
              class: "card"
            children:
              - tag: div
                attrs:
                  class: "card-body columns"
                children:
                  - tag: div
                    attrs:
                      class: "col-3"
                    children:
                      - tag: div
                        children:
                          - tag: strong
                            children:
                              - text:
                                  literal: "Category"
                      - tag: div
                        children:
                          - tag: strong
                            children:
                              - text:
                                  literal: "Debug"
                  - tag: div
                    attrs:
                      class: "col-3"
                    children:
                      - tag: div
                        children:
                          - text:
                              key: category
                              in: info
                      - tag: div
                        children:
                          - text:
                              key: debug
                              in: info
                  - tag: div
                    attrs:
                      class: "col-3"
                    children:
                      loop:
                        key: config
                      with: app_setting_name_view 

                  - tag: div
                    attrs:
                      class: "col-3"
                    children:
                      loop:
                        key: config
                      with: app_setting_value_view

    app_sections_view:
      view:
        tag: div
        children:
          - view: app_settings_view
            params:
              object:
                info:
                  key: info
                  in: data
                config:
                  key: config
                  in: data
          - view: app_modules_section_view
            params:
              object:
                modules_view:
                  key: modules_view
                  in: data
                modules:
                  key: modules
                  in: data
    app_main_view:
      view:
        view: main
        params:
          object:
            title:
              text:
                key: app
                in: data
            view:
              keyword: app_sections_view
            data:
              key: data
    app_view: 
      view:
        view: layout
        params:
          object:
            message:
              key: message
            content_view:
              keyword: app_main_view
            contents:
              object:
                app: 
                  key: app
                config:
                  key: config
                info:
                  object:
                    category:
                      key: category
                    debug:
                      key: debug
                modules:
                  key: modules
                modules_view:
                  key: modules_view
            sidebar:
              keyword: admin_sidebar
  decoders:
    app_info:
      object:
        effect:
          keyword: ws
        data:
          object:
            info:
              object:
                debug:
                  any: boolean
                category:
                  any: text
    app_config:
      object:
        effect:
          keyword: ws
        data:
          object:
            config:
              entries:
                one_of:
                  - text: any
                  - number: any
    modules:
      object:
        effect:
          keyword: ws
        data:
          object:
            modules:
              list:
                object:
                  name:
                    text: any
    no_modules:
      object:
        effect:
          keyword: ws
        data:
          object:
            modules:
              list: empty
    show_app:
      object:
        effect:
          keyword: ui
        event:
          object:
            name:
              keyword: show_app
            app:
              object:
                name: 
                  text: any
