version: 1.0
type: module
category: server
name: app_info_api 
spec:
  decoders:
    app_info_query:
      object:
        action: 
          text: 
            literal: "info"
        app:
          text: any
    app_info_found:
      object:
        app:
          any: keyword
        category: 
          any: keyword 
        debug:
          any: keyword
  encoders:
    app_info_query:
      object:
        query: 
          keyword: info
        app:
          key: app
    app_info:
      object:
        info:
          object:
            app:
              key: app
            category:
              key: category
            debug: 
              key: debug
  update:
    app_info_query:
      - when:
          encoder: is_admin
        model:
          app:
            key: app
        cmds:
          - effect: config 
            encoder: app_info_query 
      - cmds:
          - effect: notify
            encoder: forbidden
    app_info_found:
      model:
        category:
          key: category
        debug:
          key: debug
      cmds:
        - effect: notify
          encoder: app_info
