version: 1.0
type: module
category: ui
name: apps_ui
spec:
  init:
    model:
      apps: 
        list: []
      nodes:
        list: []
  update:
    apps:
      model:
        apps:
          key: data
          in: 
            key: data
      cmds:
        - effect: ui
          encoder: apps_view
    show_apps:
      cmds:
        - effect: ui
          encoder: apps_view
        - effect: ws
          encoder: apps
    ready:
      cmds:
        - effect: ui
          encoder: apps_view
        - effect: ws
          encoder: apps
  encoders:
    app_table_item_view:
      view:
        tag: "tr"
        attrs:
          key:
            key: name
            in: item
        children:
          - tag: td
            children:
              - tag: a
                attrs:
                  class: "c-hand"
                  onclick:
                    encoder: app_selection
                children:
                  - text:
                      key: name
                      in: item
          - tag: td
            children:
              - text:
                  key: category
                  in: item
    apps_table_view:
      view:
        view: table
        params:
          object:
            headers:
              list:
                - object:
                    title: 
                      text:
                        literal: "Name"
                - object:
                    title:
                      text: 
                        literal: "Category"
            items:
              key: data
            item_view:
              keyword: app_table_item_view
                    
    apps_section_view:
      view:
        view: section
        params:
          object:
            view:
              keyword: apps_table_view
            data:
              key: data
    apps_main_view:
      view:
        view: main
        params:
          object:
            title:
              text:
                literal: "Apps"
            view:
              keyword: apps_table_view
            data:
              key: data
    apps_view: 
      view:
        view: layout
        params:
          object:
            message:
              key: message
            content_view:
              keyword: apps_main_view
            contents:
              key: apps
            sidebar:
              keyword: admin_sidebar
    admin_sidebar:
      view:
        tag: div
        attrs:
          class: "text-center"
          key: "sidebar"
        children:
          - view: sidebar_icon
            params:
              object:
                name: "apps"
                style: "fa fa-4x fa-flask"
                title: "Apps"
          - view: sidebar_icon
            params:
              object:
                name: "ports"
                style: "fa fa-4x fa-rss"
                title: "Ports"
          - view: sidebar_icon
            params:
              object:
                name: "tables"
                style: "fa fa-4x fa-database"
                title: "Tables"
          - view: sidebar_icon
            params:
              object:
                name: "nodes"
                style: "fa fa-4x fa-desktop"
                title: "Nodes"
          - view: sidebar_icon
            params:
              object:
                name: "users"
                style: "fa fa-4x fa-users"
                title: "Users"
          - view: sidebar_icon
            params:
              object:
                name: "metrics"
                style: "fa fa-4x fa-area-chart"
                title: "Metrics"
          - view: sidebar_icon
            params:
              object:
                name: "bugs"
                style: "fa fa-4x fa-bug"
                title: "Bugs"
    apps:
      object: 
        action:
          keyword: apps
    nodes:
      object: 
        action:
          keyword: nodes
    app_selection:
      object:
        name:
          keyword: show_app
        app:
          key: item 
  decoders:
    ready:
      object:
        effect:
          keyword: events
        event:
          keyword: user_logged_in
    show_apps:
      object:
        effect:
          keyword: ui
        event:
          text:
            literal: "apps"
    apps:
      object:
        effect:
          keyword: ws
        data:
          object:
            type: 
              text: 
                literal: apps
            data:
              list:
                object:
                  name: 
                    text: any
                  category:
                    text: any
