version: 1.0
type: module
category: server
name: apps 
spec:
  decoders:
    list:
      object:
        action: 
          text: 
            literal: "apps"
    apps:
      object:
        apps: 
          list:
            object: 
              category:
                keyword:
                  one_of:
                    - keyword: api
                    - keyword: ui
              name:
                any: keyword
  encoders:
    apps_query:
      object:
        query: 
          keyword: apps
    apps:
      object:
        type:
          keyword: apps
        data:
          key: apps
  update:
    list:
      - when:
          member:
            roles: 
              keyword: admin
        cmds:
          - effect: config 
            encoder: apps_query
      - cmds:
          - effect: notify
            encoder: forbidden
    apps:
      model:
        apps:
          key: apps
      cmds:
        - effect: notify
          encoder: apps
