version: 1.0
type: module
category: server
name: file_upload_api 
spec:
  decoders:
    health:
      object:
        headers:
          object:
            content-length: 
              text:
                literal: "0"
    file:
      object:
        headers:
          object:
            cmauth:
              text: any
            content-length:
              number: any
            content-type:
              text: any
        body:
          data: any
    date_for_file_upload:
      object:
        context:
          keyword: file_upload
        now:
          any: number
    uuid_for_file_upload:
      object:
        context:
          keyword: file_upload
        uuid:
          any: text
    token:
      object:
        context:
          keyword: file_upload
        type:
          keyword: token
        bucket:
          config: tokens_db
        value: 
          object: 
            id:
              any: text
            subject:
              any: text
            type:
              any: text
            created:
              any: number
            ttl:
              any: number
    file_written:
      object:
        bucket:
          config: files_db
        context: 
          keyword: file_upload
        status:
          keyword: ok
  update:
    health:
      cmds:
        - effect: notify
          encoder: health
    file:
      model:
        token:
          key: cmauth
          in: headers
        file:
          key: body
        type:
          key: content-type
          in: headers
        size:
          key: content-length
          in: headers
      cmds:
        - effect: now
          encoder: file_upload_context
    date_for_file_upload:
      model:
        now:
          key: now
      cmds:
        - effect: db_get
          encoder: token_lookup
    token:
      - when:
          gt:
            - sum:
                - key: created
                  in:
                    key: value
                    in: data
                - key: ttl
                  in:
                    key: value
                    in: data
            - key: now
              in: model
        cmds:
          - effect: uuid
            encoder: file_upload_context
      - cmds:
          - effect: notify
            encoder: forbidden
    uuid_for_file_upload:
      model:
        uuid: 
          key: uuid
      cmds:
        - effect: db_put_new_all
          encoder: file_record
    file_written:
      cmds:
        - effect: notify
          encoder: file_info
  encoders:
    health:
      object:
        status: 
          keyword: ok
    file_upload_context:
      object:
        context:
          keyword: file_upload
    token_lookup:
      object:
        context:
          keyword: file_upload
        bucket:
          config: tokens_db
        type:
          keyword: token
        id:
          key: token
    file_record:
      object:
        context: 
          keyword: file_upload
        bucket:
          config: files_db
        items: 
          list:
            - object:
                type: 
                  keyword: file
                id:
                  key: uuid
                value:
                  object:
                    id:
                      key: uuid
                    created:
                      key: now
                    type:
                      key: type
                    size:
                      key: size
                    token:
                      key: token
                    data:
                      key: file
    file_info:
      object:
        status:
          keyword: ok
        id:
          key: uuid
        size: 
          key: size
        type:
          key: type
        created:
          key: now
