version: 1.0
type: module
category: server
name: modules_api 
spec:
  decoders:
    modules_query:
      object:
        action: 
          text: 
            literal: "modules"
        app:
          text: any
    modules:
      object:
        modules: 
          list:
            object: 
              name:
                any: keyword
              status:
                any: keyword
  encoders:
    modules_query:
      object:
        query: 
          keyword: modules
        scope:
          key: app
    modules:
      object:
        modules:
          key: modules
  update:
    modules_query:
      - when:
          member:
            roles: 
              keyword: admin
        model:
          app:
            key: app
        cmds:
          - effect: config 
            encoder: modules_query 
      - cmds:
          - effect: notify
            encoder: forbidden
    modules:
      model:
        modules:
          key: modules 
      cmds:
        - effect: notify
          encoder: modules
