version: 1.0
type: module
category: server
name: ports_api 
spec:
  decoders:
    ports_query:
      object:
        action: 
          text: 
            literal: "ports"
    ports:
      object:
        ports: 
          list:
            object: 
              apps:
                list: 
                  object:
                    name:
                      any: keyword
                    mounts:
                      list:
                        object:
                          path:
                            any: text
                          transport:
                            any: keyword

              name:
                any: keyword
              port:
                any: number
  encoders:
    ports_query:
      object:
        query: 
          keyword: ports 
    ports:
      object:
        type:
          keyword: ports
        data:
          key: ports
  update:
    ports_query:
      - when:
          encoder: is_admin
        cmds:
          - effect: config 
            encoder: ports_query
      - cmds:
          - effect: notify
            encoder: forbidden
    ports:
      model:
        ports:
          key: ports 
      cmds:
        - effect: notify
          encoder: ports
