version: 1.0
type: module
category: ui
name: ports_ui
spec:
  init:
    model:
      ports:
        list: []
  update:
    ports:
      model:
        ports:
          key: data
          in: 
            key: data
      cmds:
        - effect: ui
          encoder: ports_view
    show_ports:
      cmds:
        - effect: ui
          encoder: ports_view
        - effect: ws
          encoder: ports
  encoders:
    port_app_mount_item_view:
      view:
        tag: div
        attrs:
          class: "columns col-12"
        children:
          - tag: div
            attrs:
              class: "col-6"
            children:
              - tag: strong
                children:
                  - text:
                      key: transport
                      in: item
          - tag: div
            attrs:
              class: "col-6"
            children:
              - text:
                  key: path
                  in: item
    port_app_mounts_view:
      view:
        tag: div
        children:
          loop:
            key: mounts
          with: port_app_mount_item_view
    port_app_item_view:
      view:
        tag: div
        attrs:
          class: "columns mb-6"
          key: 
            key: name
            in: item
        children:
          - tag: div
            attrs:
              class: "col-6"
            children:
              - tag: a
                attrs:
                  class: "c-hand"
                  onclick:
                    encoder: app_selection
                  href: "#" 
                children: 
                  - text:
                      key: name
                      in: item
          - tag: div
            attrs:
              class: "col-6"
            children:
              - view: port_app_mounts_view
                params:
                  object:
                    mounts:
                      key: mounts
                      in: item
    port_apps_view:
      view:
        tag: div
        attrs:
          class: "container"
        children:
          loop:
            key: apps
          with: port_app_item_view
    port_table_item_view:
      view:
        tag: "tr"
        attrs:
          key:
            key: name
            in: item
        children:
          - tag: td
            children:
              - text:
                  key: port 
                  in: item
          - tag: td
            children:
              - view: port_apps_view
                params:
                  object:
                    apps:
                      key: apps
                      in: item
    ports_table_view:
      view:
        view: table
        params:
          object:
            headers:
              list:
                - object:
                    title: 
                      text:
                        literal: "Port"
                - object:
                    title:
                      text: 
                        literal: "Apps"
            items:
              key: data
            item_view:
              keyword: port_table_item_view
                    
    ports_section_view:
      view:
        view: section
        params:
          object:
            view:
              keyword: ports_table_view
            data:
              key: data
    ports_main_view:
      view:
        view: main
        params:
          object:
            title:
              text:
                literal: "ports"
            view:
              keyword: ports_table_view
            data:
              key: data
    ports_view: 
      view:
        view: layout
        params:
          object:
            message:
              key: message
            content_view:
              keyword: ports_main_view
            contents:
              key: ports
            sidebar:
              keyword: admin_sidebar
    ports:
      object: 
        action:
          keyword: ports 
  decoders:
    show_ports:
      object:
        effect:
          keyword: ui
        event:
          text:
            literal: "ports"
    ports:
      object:
        effect:
          keyword: ws
        data:
          object:
            type: 
              text: 
                literal: ports
            data:
              list:
                object:
                  name:
                    text: any
                  port: 
                    number: any
                  apps:
                    list:
                      object:
                        name:
                          text: any
                        mounts:
                          list:
                            object:
                              transport:
                                text: any
                              path:
                                text: any

