version: 1.0
type: module
category: server
name: projects_api 
spec:
  decoders:
    list_projects:
      object:
        action: 
          text: 
            literal: "projects"
    create_project:
      object:
        action: 
          text: 
            literal: "create_project"
        name:
          any: text
        description:
          any: text
    edit_project:
      object:
        action: 
          text: 
            literal: "edit_project"
        project:
          any: text
        name:
          any: text
        description:
          any: text
    projects:
      object:
        bucket:
          keyword: tracker
        type: 
          keyword: project
        values: 
          list:
            object: 
              status:
                keyword:
                  one_of:
                    - keyword: planning
                    - keyword: started
                    - keyword: abandoned
              name:
                any: keyword
              description:
                any: text
              owner:
                any: text
    project_found:
      object:
        bucket:
          keyword: tracker
        type: 
          keyword: project
        value:
          object:
            id:
              any: text
            status:
              one_of:
                - keyword: planning
                - keyword: started
                - keyword: abandoned
    project_owner:
      object:
        bucket:
          keyword: tracker
        type: 
          keyword: owner 
        value:
          any: text
    project_not_found:
      object:
        bucket:
          keyword: tracker
        type: 
          keyword: project
        error:
          keyword: not_found
    tracker_written:
      object:
        bucket: 
          keyword: tracker
        status:
          keyword: ok
  encoders:
    projects_lookup:
      object:
        bucket:
          keyword: tracker
        type:
          keyword: project
    project_lookup:
      object:
        bucket:
          keyword: tracker
        type:
          keyword: project
        id:
          key: project
    project_owner_lookup:
      object:
        bucket:
          keyword: tracker
        type:
          keyword: owner
        id:
          key: project
    projects:
      object:
        projects:
          key: projects
    project_entries:
      object:
        context:
          keyword: new_project
        bucket:
          keyword: tracker
        items:
          list:
            - object: 
                type: 
                  keyword: project
                id: 
                  key: name
                value:
                  key: uuid
            - object:
                type:
                  keyword: project
                id:
                  key: uuid
                value:
                  object:
                    name: 
                      key: name
                    description: 
                      key: description
                    status:
                      key: project_status
                    id:
                      key: uuid
            - object:
                type:
                  keyword: owner
                id:
                  key: uuid
                value:
                  key: id
                  in:
                    key: user
            - object:
                type:
                  keyword: projects
                id:
                  key: id
                  in:
                    key: user
                value:
                  key: uuid
    updated_project:
      object:
        context:
          keyword: edit_project
        bucket:
           keyword: tracker
        items:
          list:
            - object:
                type:
                  keyword: project
                id:
                  key: uuid
                value:
                  object:
                    name:
                      key: name
                    description:
                      key: description
                    status:
                      key: status
                      in: project
                    id:
                      key: id
                      in: project
    project:
      object:
        project:
          object:
            name: 
              key: name
            description:
              key: description
            id:
              key: uuid
            status:
              key: project_status
            owner:
              key: id
              in:
                key: user
  update:
    list_projects:
      - when:
          encoder: is_admin
        cmds:
          - effect: db_get
            encoder: projects_lookup
      - cmds:
          - effect: notify
            encoder: forbidden
    uuid:
      - when:
          eq:
            - key: state 
              in: model
            - keyword: creating_project
        model:
          uuid:
            key: uuid
          project_status:
            keyword: planning
        cmds:
            - effect: db_put_new_all
              encoder: project_entries
    create_project:
      - when:
          encoder: is_admin
        model:
          name:
            key: name
          description:
            key: description
          state:
            keyword: creating_project
        cmds:
          - effect: uuid
      - cmds:
          - effect: notify
            encoder: forbidden
    edit_project:
      - when:
          encoder: is_admin
        model:
          project:
            key: project
          name:
            key: name
          description:
            key: description
          state:
            keyword: editing_project
        cmds:
          - effect: db_get
            encoder: project_owner_lookup
      - cmds:
          - effect: notify
            encoder: forbidden
    project_owner:
      - when:
          eq:
            - key: value
              in: data
            - key: id
              in:
                key: user
                in: model
        cmds:
          - effect: db_get
            encoder: project_lookup
      - cmds:
          - effect: notify
            encoder: forbidden
    project_found:
      model:
        project:
          key: value
      cmds:
        - effect: db_put_all
          encoder: updated_project
    project_not_found:
      cmds:
        - effect: notify
          encoder: not_found
    tracker_written:
      cmds:
        - effect: notify
          encoder: project
    projects:
      model:
        projects:
          key: values
      cmds:
        - effect: notify
          encoder: projects
