version: 1.0
type: module
category: server
name: register_api 
spec:
  decoders:
    register:
      object:
        action:
          text:
            literal: "register"
        first:
          text: any
        last:
          text: any
        username:
          email: any
        password:
          text: any
        password_confirm:
          text: any
    not_found:
      object:
        context:
          keyword: register
        error:
          keyword: not_found
    found:
      object:
        context:
          keyword: register
        value:
          text: any
    uuid_for_new_user:
      object:
        context:
          keyword: register
        uuid:
          text: any
    registered:
      object:
        context:
          keyword: register
        bucket: 
          keyword: users
        status:
          keyword: ok
  encoders:
    register_user_lookup:
      object:
        context:
          keyword: register
        bucket:
          keyword: users
        type:
          keyword: email
        id: 
          key: email
    conflict:
      object:
        error:
          keyword: conflict
    ok:
      object:
        status:
          keyword: ok
    register_data:
      object:
        context:
          keyword: register
        bucket:
          keyword: users
        new:
          keyword: true
        items:
          list:
            - object: 
                type: 
                  keyword: email
                id: 
                  key: email
                value:
                  key: uuid
            - object:
                type: 
                  keyword: password
                id: 
                  key: uuid
                value:
                  key: password
            - object:
                type: 
                  keyword: roles
                id: 
                  key: uuid
                value: 
                  list:
                    - config: role 
            - object:
                type:
                  keyword: user
                id:
                  key: uuid
                value:
                  object:
                    first: 
                      key: first
                    last: 
                      key: last
                    email:
                      key: email
                    id:
                      key: uuid
    user_data:
      object:
        id: 
          key: uuid
        first:
          key: first
        last: 
          key: last
        email:
          key: email
    register_context:
      object:
        context:
          keyword: register
  update:
    register:
      - when:
          eq:
            - key: password
              in: data
            - key: password_confirm
              in: data
        model:
          first: 
            key: first
          last: 
            key: last
          email:
            key: username
          password:
            key: password
        cmds:
          - effect: db_get
            encoder: register_user_lookup
      - cmds:
        - effect: notify
          encoder: invalid
    found:
      cmds:
        - effect: notify
          encoder: conflict
    not_found:
      model:
        state: 
          keyword: registering
      cmds:
        - effect: uuid
          encoder: register_context 
    uuid_for_new_user:
      model:
        uuid:
          key: uuid
      cmds:
        - effect: db_put
          encoder: register_data
    registered:
      cmds:
        - effect: notify
          encoder: user_data
