version: 1.0
type: module
category: server
name: register_api 
spec:
  decoders:
    register:
      object:
        action:
          text:
            literal: "register"
        first:
          text: any
        last:
          text: any
        username:
          email: any
        password:
          text: any
        password_confirm:
          text:
            same_as: password
    not_found:
      object:
        context:
          keyword: register
        error:
          keyword: not_found
    found:
      object:
        context:
          keyword: register
        value:
          text: any
    uuid:
      object:
        uuid:
          text: any
    registered:
      object:
        context:
          keyword: register
        bucket: 
          keyword: users
        status:
          keyword: ok
  encoders:
    register_user_lookup:
      object:
        context:
          keyword: register
        bucket:
          keyword: users
        type:
          keyword: email
        id: 
          key: email
    conflict:
      object:
        error:
          keyword: conflict
    ok:
      object:
        status:
          keyword: ok
    register_data:
      object:
        context:
          keyword: register
        bucket:
          keyword: users
        items:
          list:
            - object: 
                type: 
                  keyword: email
                id: 
                  key: email
                value:
                  key: uuid
            - object:
                type: 
                  keyword: password
                id: 
                  key: uuid
                value:
                  key: password
            - object:
                type: 
                  keyword: roles
                id: 
                  key: uuid
                value: 
                  list:
                    - config: role 
            - object:
                type:
                  keyword: user
                id:
                  key: uuid
                value:
                  object:
                    first: 
                      key: first
                    last: 
                      key: last
                    email:
                      key: email
                    id:
                      key: uuid
    user_data:
      object:
        id: 
          key: uuid
        first:
          key: first
        last: 
          key: last
        email:
          key: email
  update:
    register:
      model:
        first: 
          key: first
        last: 
          key: last
        email:
          key: username
        password:
          key: password
      cmds:
        - effect: db_get
          encoder: register_user_lookup
    found:
      cmds:
        - effect: notify
          encoder: conflict
    not_found:
      model:
        state: 
          keyword: registering
      cmds:
        - effect: uuid
    uuid:
      - when: 
          eq:
            - keyword: registering
            - key: state
        model:
          uuid:
            key: uuid
        cmds:
          - effect: db_put_new_all
            encoder: register_data
    registered:
      cmds:
        - effect: notify
          encoder: user_data
