version: 1.0
type: module
category: ui
name: tests_ui
spec:
  init:
    model:
      tests: []
      test: {}
  decoders:
    show_tests:
      object:
        effect:
          keyword: ui
        event:
          text: 
            literal: "tests"
    show_test:
      object:
        effect:
          keyword: ui
        event:
          object:
            name: 
              keyword: "show_test"
            test:
              any: text
    show_scenario:
      object:
        effect:
          keyword: ui
        event:
          object:
            name: 
              keyword: "show_scenario"
            test:
              any: text
            scenario:
              any: text
    show_background:
      object:
        effect:
          keyword: ui
        event:
          object:
            name: 
              keyword: "show_background"
            test:
              any: text
            background:
              any: text
    tests:
      object:
        effect:
          keyword: ws
        data:
          object:
            tests:
              list:
                object:
                  name: 
                    any: text
                  backgrounds:
                    any: number
                  scenarios:
                    any: number
    test:
      object:
        effect:
          keyword: ws
        data:
          object:
            test:
              object:
                name:
                  any: text
                scenarios:
                  list:
                    object:
                      title:
                        any: text
                backgrounds:
                  list:
                    object:
                      title:
                        any: text
    scenario:
      object:
        effect:
          keyword: ws
        data:
          object:
            scenario:
              object:
                test:
                  any: text
                title:
                  any: text
                tags:
                  any: list
                steps:
                  any: list
                backgrounds:
                  any: list
    background:
      object:
        effect:
          keyword: ws
        data:
          object:
            background:
              object:
                test:
                  any: text
                title:
                  any: text
                tags:
                  any: list
                steps:
                  any: list
                scenarios:
                  any: list
  update:
    show_tests:
      cmds:
        - effect: ui
          encoder: tests_view
        - effect: ws
          encoder: tests
    tests:
      model:
        tests:
          key: tests
          in: 
            key: data
      cmds:
        - effect: ui
          encoder: tests_view
    show_test:
      model:
        test: 
          key: test
          in: event
      cmds:
        - effect: ws
          encoder: test_info
    show_scenario:
      model:
        scenario: 
          key: scenario
          in: event
      cmds:
        - effect: ws
          encoder: scenario_info
    show_background:
      model:
        background: 
          key: background
          in: event
      cmds:
        - effect: ws
          encoder: background_info
    test:
      model:
        test:
          key: test
          in: data
      cmds:
        - effect: ui
          encoder: test_view
    scenario:
      model:
        scenario:
          key: scenario
          in: data
      cmds:
        - effect: ui
          encoder: scenario_view
    background:
      model:
        background:
          key: background
          in: data
      cmds:
        - effect: ui
          encoder: background_view
  encoders:
    tests:
      object:
        action: tests
    test_selection:
      object:
        name:
          keyword: show_test
        test:
          key: name
          in: item
    scenario_selection:
      object:
        name:
          keyword: show_scenario
        scenario:
          key: title
          in: item
        test:
          key: test
          in: context
    background_selection:
      object:
        name:
          keyword: show_background
        background:
          key: title
          in: item
        test:
          key: test
          in: context
    test_info:
      object:
        action: 
          keyword: test
        test:
          key: test
    scenario_info:
      object:
        action:
          keyword: scenario
        test:
          key: name
          in: test
        scenario:
          key: scenario
    background_info:
      object:
        action:
          keyword: background
        test:
          key: name
          in: test
        background:
          key: background
    test_table_item_view:
      view:
        tag: "tr"
        attrs:
          key:
            key: name
            in: item
        children:
          - tag: td
            children:
              - tag: a
                attrs:
                  class: "c-hand"
                  onclick:
                    encoder: test_selection
                children:
                  - text:
                      key: name
                      in: item
          - tag: td
            children:
              - text:
                  key: backgrounds 
                  in: item
          - tag: td
            children:
              - text:
                  key: scenarios 
                  in: item
    tests_table_view:
      view:
        view: table
        params:
          object:
            headers:
              list:
                - object:
                    title: 
                      text:
                        literal: "Name"
                - object:
                    title:
                      text: 
                        literal: "Backgrounds"
                - object:
                    title:
                      text: 
                        literal: "Scenarios"
            items:
              key: tests
            item_view:
              keyword: test_table_item_view
    tests_sections_view:
      view:
        tag: div
        children:
          - view: tests_table_view
            params:
              object:
                tests:
                  key: tests
                  in: data
    tests_main_view:
      view:
        view: main
        params:
          object:
            title:
              text:
                literal: "Tests"
            view:
              keyword: tests_sections_view
            data:
              key: data
    tests_view:
      view:
        view: layout
        params:
          object:
            message:
              key: message
            content_view:
              keyword: tests_main_view
            contents:
              object:
                tests: 
                  key: tests
                test:
                  key: test
            sidebar:
              keyword: admin_sidebar
    test_scenario_tag_view:
      view:
        tag: span
        attrs:
          class: "mr-2 label label-rounded tag"
        children:
          - text:
              key: item
    test_scenario_tags_view:
      view:
        tag: div
        children:
          loop:
            key: data 
          with: test_scenario_tag_view
    test_scenario_table_item_view:
      view:
        tag: "tr"
        attrs:
          key:
            key: title
            in: item
        children:
          - tag: td
            children:
              - view: scenario_link_view
                params:
                  object:
                    item: 
                      key: item
                    context:
                      key: context
    test_scenarios_table_view:
      view:
        view: table
        params:
          object:
            headers:
              list:
                - object:
                    title: 
                      text:
                        literal: "Name"
            items:
              key: scenarios
            context:
              object:
                test:
                  key: test
            item_view:
              keyword: test_scenario_table_item_view
    test_scenarios_view:
      view: 
        tag: div
        children:
          - tag: h4
            children:
              - text:
                  literal: "Scenarios"
          - view: test_scenarios_table_view
            params:
              object:
                test:
                  key: test
                scenarios:
                  key: scenarios
    background_link_view:
      view:
        tag: a
        attrs:
          class: "c-hand"
          onclick:
            encoder: background_selection
        children:
          - text:
              key: title
              in: item
    background_links_view:
      view:
        tag: div
        attrs:
          class: "links"
        children:
          loop:
            key: backgrounds
            in: data
          context:
            object:
              test:
                key: test
                in: data
          with: background_link_view
    scenario_link_view:
      view:
        tag: a
        attrs:
          class: "c-hand"
          onclick:
            encoder: scenario_selection
        children:
          - text:
              key: title
              in: item
    scenario_links_view:
      view:
        tag: div
        attrs:
          class: "links"
        children:
          loop:
            key: scenarios
            in: data
          context:
            object:
              test:
                key: test
                in: data
          with: scenario_link_view
    test_background_table_item_view:
      view:
        tag: "tr"
        attrs:
          key:
            key: title
            in: item
        children:
          - tag: td
            children:
              - view: background_link_view
                params:
                  object:
                    item: 
                      key: item
                    context:
                      key: context
    test_backgrounds_table_view:
      view:
        view: table
        params:
          object:
            headers:
              list:
                - object:
                    title: 
                      text:
                        literal: "Name"
            items:
              key: backgrounds
            context:
              object:
                test:
                  key: test
            item_view:
              keyword: test_background_table_item_view
    test_backgrounds_view:
      view: 
        tag: div
        attrs:
          class: "mt-4"
        children:
          - tag: h4
            attrs:
              class: "mt-2"
            children:
              - text:
                  literal: "Backgrounds"
          - view: test_backgrounds_table_view
            params:
              object:
                test:
                  key: test
                backgrounds:
                  key: backgrounds
    test_sections_view:
      view:
        tag: div
        children:
          - view: test_scenarios_view
            params:
              object:
                test:
                  key: name 
                  in: data
                scenarios:
                  key: scenarios
                  in: data
          - view: test_backgrounds_view
            params:
              object:
                test:
                  key: name 
                  in: data
                backgrounds:
                  key: backgrounds
                  in: data

    test_main_view:
      view:
        view: main
        params:
          object:
            title:
              key: name
              in:
                key: test
                in: data
            view:
              keyword: test_sections_view
            data:
              key: test
              in: data
    test_view:
      view:
        view: layout
        params:
          object:
            message:
              key: message
            content_view:
              keyword: test_main_view
            contents:
              object:
                test: 
                  key: test
            sidebar:
              keyword: admin_sidebar
    
    scenario_info_view:
      view:
        view: info_view
        params:
          object:
            title: 
              text:
                literal: "Scenario info"
            items:
              list:
                - object:
                    title:
                      text:
                        literal: "Test"
                    value:
                      key: test
                    view:
                      keyword: text_view
                - object:
                    title:
                      text: 
                        literal: "Tags"
                    value:
                      key: tags
                    view:
                      keyword: test_scenario_tags_view
                - object:
                    title:
                      text: 
                        literal: "Backgrounds"
                    value:
                      object:
                        test:
                          key: test
                        backgrounds:
                          key: backgrounds
                    view:
                      keyword: background_links_view
    scenario_step_table_item_view:
      view:
        tag: "tr"
        attrs:
          key:
            key: title
            in: item
        children:
          - tag: td
            children:
              - text:
                  key: title
                  in: item
          - tag: td
            children:
              - view: json_view
                params:
                  object:
                    source:
                      object:
                        type:
                          key: type
                          in: item
                        spec:
                          key: spec
                          in: item
    scenario_steps_table_view:
      view:
        view: table
        params:
          object:
            headers:
              list:
                - object:
                    title: 
                      text:
                        literal: "Name"
                - object:
                    title: 
                      text:
                        literal: "Spec"
            items:
              key: steps
            item_view:
              keyword: scenario_step_table_item_view
    scenario_steps_view:
      view:
        tag: div
        attrs:
          class: "mt-4"
        children:
          - tag: h4
            attrs:
              class: "mt-2"
            children:
              - text:
                  literal: "Steps"
          - view: scenario_steps_table_view
            params:
              object:
                steps:
                  key: steps
    scenario_sections_view:
      view:
        tag: div
        children:
          - view: scenario_info_view
            params:
              key: data
          - view: scenario_steps_view
            params:
              key: data
    scenario_main_view:
      view:
        view: main
        params:
          object:
            title:
              key: title 
              in:
                key: scenario
                in: data
            view:
              keyword: scenario_sections_view
            data:
              key: scenario
              in: data
    scenario_view:
      view:
        view: layout
        params:
          object:
            message:
              key: message
            content_view:
              keyword: scenario_main_view
            contents:
              object:
                scenario: 
                  key: scenario
            sidebar:
              keyword: admin_sidebar
    background_info_view:
      view:
        view: info_view
        params:
          object:
            title: 
              text:
                literal: "Background info"
            items:
              list:
                - object:
                    title:
                      text:
                        literal: "Test"
                    value:
                      key: test
                    view:
                      keyword: text_view
                - object:
                    title:
                      text: 
                        literal: "Tags"
                    value:
                      key: tags
                    view:
                      keyword: test_scenario_tags_view
                - object:
                    title:
                      text: 
                        literal: "Scenarios"
                    value:
                      object:
                        test:
                          key: test
                        scenarios:
                          key: scenarios
                    view:
                      keyword: scenario_links_view
    background_step_table_item_view:
      view:
        tag: "tr"
        attrs:
          key:
            key: title
            in: item
        children:
          - tag: td
            children:
              - text:
                  key: title
                  in: item
          - tag: td
            children:
              - view: json_view
                params:
                  object:
                    source:
                      object:
                        type:
                          key: type
                          in: item
                        spec:
                          key: spec
                          in: item
    background_steps_table_view:
      view:
        view: table
        params:
          object:
            headers:
              list:
                - object:
                    title: 
                      text:
                        literal: "Name"
                - object:
                    title: 
                      text:
                        literal: "Spec"
            items:
              key: steps
            item_view:
              keyword: background_step_table_item_view
    background_steps_view:
      view:
        tag: div
        attrs:
          class: "mt-4"
        children:
          - tag: h4
            attrs:
              class: "mt-2"
            children:
              - text:
                  literal: "Steps"
          - view: background_steps_table_view
            params:
              object:
                steps:
                  key: steps
    background_sections_view:
      view:
        tag: div
        children:
          - view: background_info_view
            params:
              key: data
          - view: background_steps_view
            params:
              key: data
    background_main_view:
      view:
        view: main
        params:
          object:
            title:
              key: title
              in:
                key: background 
                in: data
            view:
              keyword: background_sections_view
            data:
              key: background
              in: data
    background_view:
      view:
        view: layout
        params:
          object:
            message:
              key: message
            content_view:
              keyword: background_main_view
            contents:
              object:
                background: 
                  key: background
            sidebar:
              keyword: admin_sidebar
