version: 1.0
type: module
category: server
name: tests_api 
spec:
  decoders:
    list_tests:
      object:
        action: 
          text: 
            literal: "tests"
    single_test:
      object:
        action: 
          text: 
            literal: "test"
        test:
          any: text
    scenario_query:
      object:
        action:
          text:
            literal: "scenario"
        test:
          any: text
        scenario:
          any: text
    tests:
      object:
        tests:
          list: any
    test:
      object:
        test:
          object:
            name: 
              any: keyword
            scenarios:
              any: list
            backgrounds:
              any: list
    scenario:
      object:
        scenario:
          object:
            test:
              any: text
            title:
              any: text
            steps:
              any: list
            backgrounds:
              any: list
            tags:
              any: list
            purpose: 
              any: text
    no_such_scenario:
      object:
        scenario:
          object:
            test:
              any: text
            title:
              any: text
            error:
              keyword: not_found
  update:
    list_tests:
      - when:
          encoder: is_admin
        cmds:
          - effect: test
            encoder: tests_query
      - cmds:
          - effect: notify
            encoder: forbidden
    single_test:
      - when:
          encoder: is_admin
        model:
          test:
            key: test
        cmds:
          - effect: test
            encoder: test_query
      - cmds:
          - effect: notify
            encoder: forbidden
    scenario_query:
      - when:
          encoder: is_admin
        model:
          test:
            key: test
          scenario:
            key: scenario
        cmds:
          - effect: test
            encoder: scenario_query
      - cmds:
          - effect: notify
            encoder: forbidden
    tests:
      model:
        tests:
          key: tests
      cmds:
        - effect: notify
          encoder: tests
    test:
      model:
        test:
          key: test
      cmds:
        - effect: notify
          encoder: test
    scenario:
      model:
        scenario:
          key: scenario
      cmds:
        - effect: notify
          encoder: scenario
    no_such_scenario:
      model:
        scenario:
          key: scenario
      cmds:
        - effect: notify
          encoder: scenario
  encoders:
    tests:
      object:
        tests:
          key: tests
    test:
      object:
        test:
          key: test
    scenario:
      object:
        scenario:
          key: scenario
    tests_query:
      object:
        query:
          keyword: tests
    test_query:
      object:
        query:
          keyword: test
        test:
          key: test
    scenario_query:
      object:
        query:
          keyword: scenario
        test:
          key: test
        scenario:
          key: scenario
    
