version: 1.0
type: module
category: server
name: tests_api 
spec:
  decoders:
    list_tests:
      object:
        action: 
          text: 
            literal: "tests"
    single_test:
      object:
        action: 
          text: 
            literal: "test"
        test:
          any: text
    scenario_query:
      object:
        action:
          text:
            literal: "scenario"
        test:
          any: text
        scenario:
          any: text
    background_query:
      object:
        action:
          text:
            literal: "background"
        test:
          any: text
        background:
          any: text
    schedule_test:
      object:
        action:
          text:
            literal: "schedule"
        test:
          any: text
    clear_scheduled_tests:
      object:
        action:
          text:
            literal: "clear_tests"
    test_reports_query:
      object:
        action:
          text:
            literal: "test_reports"
        days:
          any: number
    tests:
      object:
        tests:
          list: any
    tests_status:
      object:
        tests:
          one_of:
            - any: object
            - any: keyword
    test:
      object:
        test:
          object:
            name: 
              any: keyword
            scenarios:
              any: list
            backgrounds:
              any: list
    background:
      object:
        background:
          object:
            test:
              any: text
            title: 
              any: text
            scenarios:
              any: list
            steps:
              any: list
            tags:
              any: list
    scenario:
      object:
        scenario:
          object:
            test:
              any: text
            title:
              any: text
            steps:
              any: list
            backgrounds:
              any: list
            tags:
              any: list
    no_such_scenario:
      object:
        scenario:
          object:
            test:
              any: text
            title:
              any: text
            error:
              keyword: not_found
    test_reports:
      object:
        test_reports:
          list:
            one_of:
              - object:
                  query:
                    any: keyword
                  status:
                    keyword: error
                  error:
                    any: data
              - object:
                  query: 
                    any: keyword
                  millis:
                    any: number
                  status:
                    keyword: ok
                  scenarios:
                    object:
                      fail:
                        any: number
                      success:
                        any: number
                      total:
                        any: number
  update:
    list_tests:
      - when:
          encoder: is_admin
        cmds:
          - effect: test
            encoder: tests_query
      - cmds:
          - effect: notify
            encoder: forbidden
    single_test:
      - when:
          encoder: is_admin
        model:
          test:
            key: test
        cmds:
          - effect: test
            encoder: test_query
      - cmds:
          - effect: notify
            encoder: forbidden
    scenario_query:
      - when:
          encoder: is_admin
        model:
          test:
            key: test
          scenario:
            key: scenario
        cmds:
          - effect: test
            encoder: scenario_query
      - cmds:
          - effect: notify
            encoder: forbidden
    background_query:
      - when:
          encoder: is_admin
        model:
          test:
            key: test
          background:
            key: background
        cmds:
          - effect: test
            encoder: background_query
      - cmds:
          - effect: notify
            encoder: forbidden
    schedule_test:
      - when:
          encoder: is_admin
        model:
          test:
            key: test
        cmds:
          - effect: test
            encoder: test_schedule_request
      - cmds:
          - effect: notify
            encoder: forbidden
    clear_scheduled_tests:
      - when:
          encoder: is_admin
        cmds:
          - effect: test
            encoder: clear_queue_request
      - cmds:
          - effect: notify
            encoder: forbidden
    test_reports_query:
      - when:
          encoder: is_admin
        model:
          days:
            key: days
        cmds:
          - effect: test
            encoder: test_reports_query
      - cmds:
          - effect: notify
            encoder: forbidden
    tests:
      model:
        tests:
          key: tests
      cmds:
        - effect: notify
          encoder: tests
    test:
      model:
        test:
          key: test
      cmds:
        - effect: notify
          encoder: test
    scenario:
      model:
        scenario:
          key: scenario
      cmds:
        - effect: notify
          encoder: scenario
    no_such_scenario:
      model:
        scenario:
          key: scenario
      cmds:
        - effect: notify
          encoder: scenario
    background: 
      model:
        background:
          key: background
      cmds:
        - effect: notify
          encoder: background
    tests_status:
      model:
        status:
          key: tests
      cmds:
        - effect: notify
          encoder: tests_status
    test_reports:
      model:
        reports:
          key: test_reports
      cmds:
        - effect: notify
          encoder: test_reports
  encoders:
    tests:
      object:
        tests:
          key: tests
    test:
      object:
        test:
          key: test
    scenario:
      object:
        scenario:
          key: scenario
    background:
      object:
        background:
          key: background
    tests_query:
      object:
        query:
          keyword: tests
    test_query:
      object:
        query:
          keyword: test
        test:
          key: test
    scenario_query:
      object:
        query:
          keyword: scenario
        test:
          key: test
        scenario:
          key: scenario
    background_query:
      object:
        query:
          keyword: background
        test:
          key: test
        background:
          key: background
    test_schedule_request:
      object:
        query:
          keyword: schedule
        test:
          key: test
    tests_status:
      object:
        tests:
          key: status
    clear_queue_request:
      object:
        query: 
          keyword: clear_queue
    test_reports_query:
      object:
        query:
          keyword: reports
        days: 
          key: days
    test_reports:
      object:
        test_reports:
          key: reports
