version: 1.0
category: api
type: module
name: weekonekt_import_api
spec:
  decoders:
    list_imports:
      object:
        action:
          text:
            literal: "imports"
    create_import:
      object:
        action:
          text:
            literal: "create_import"
    imports:
      object:
        context:
          keyword: imports
        values:
          list: any
    uuid_for_import:
      object:
        context:
          keyword: import
        uuid:
          any: text
    date_for_import:
      object:
        context:
          keyword: new_import
        now:
          any: number
    import_created:
      object:
        context:
          keyword: new_import
        status:
          keyword: ok
    wordpress_attached:
      object:
        context:
          keyword: import_attachment
        status:
          keyword: ok
    import_data:
      object:
        bucket:
          keyword: weekonekt
        type:
          keyword: import
        value:
          object:
            id:
              any: text
            status:
              any: keyword
            created:
              any: number
    attach_wordpress:
      object:
        action: 
          text:
            literal: "attach"
        file:
          any: text
        import:
          any: text
  encoders:
    imports_query:
      object:
        context: 
          keyword: imports
        bucket:
          keyword: weekonekt
        type:
          keyword: import
    import_query:
      object:
        context:
          keyword: import
        bucket:
          keyword: weekonekt
        type:
          keyword: import
        id:
          key: uuid
    uuid_for_import:
      object:
        context:
          keyword: import
    date_for_import:
      object:
        context:
          keyword: new_import
    import_entries:
      object:
        context: 
          keyword: new_import
        bucket:
          keyword: weekonekt
        new:
          keyword: true
        items: 
          list:
            - object:
                type: 
                  keyword: import
                id:
                  key: uuid
                value:
                  object:
                    id:
                      key: uuid
                    status:
                      keyword: new
                    created:
                      key: date
    imports:
      object:
        imports:
          key: imports
    import:
      object:
        import:
          key: import
    import_attachment_record:
      object:
        context: 
          keyword: import_attachment
        bucket: 
          keyword: weekonekt
        type:
          keyword: wordpress
        id: 
          key: uuid
        value:
          key: file
        new:
          keyword: true
    attachment_summary:
      object:
        file:
          key: file
        import:
          key: uuid
        status:
          keyword: ok

  update:
    list_imports:
      - when:
          encoder: is_weekonekt_admin
        cmds:
          - effect: db_get
            encoder: imports_query
      - cmds:
          - effect: notify
            encoder: forbidden
    create_import:
      - when:
          encoder: is_weekonekt_admin
        cmds:
          - effect: uuid
            encoder: uuid_for_import
      - cmds:
          - effect: notify
            encoder: forbidden
    uuid_for_import:
      model:
        uuid:
          key: uuid
      cmds:
        - effect: now
          encoder: date_for_import
    date_for_import:
      model:
        date:
          key: now
      cmds:
        - effect: db_put
          encoder: import_entries
    import_created:
      cmds:
        - effect: db_get
          encoder: import_query
    imports:
      model:
        imports: 
          key: values
      cmds:
        - effect: notify
          encoder: imports
    import_data:
      model:
        import:
          key: value
      cmds:
        - effect: notify
          encoder: import
    attach_wordpress:
      - when:
          eq:
            - key: id
              in: 
                key: import
                in: model
            - key: import
              in: data
        model:
          file:
            key: file
        cmds:
          - effect: db_put
            encoder: import_attachment_record
      - cmds:
          - effect: notify
            encoder: forbidden
    wordpress_attached:
      cmds:
        - effect: notify
          encoder: attachment_summary
