version: 1.0
type: module
category: ui
name: weekonekt_admin_import_ui
spec:
  effects:
    file:
      type: elementary-http
      settings:
        secure:
          keyword: no 
        path:
          text:
            literal: "/files"
  init:
    model:
      import_action_view: 
        keyword: import_selectfile_view
      import: []
      files: []
      import_progress: 
        number: 50
      stage:
        text: 
          literal: "Not started"
  update:
    show_import_ui:
      model:
        import_action_view:
          keyword: import_selectfile_view
      cmds:
        - effect: ui
          encoder: import_layout_view
    import_file_selected:
      model:
        import_action_view: 
          keyword: import_upload_summary_view
        files:
          key: value
      cmds:
        - effect: ui
          encoder: import_layout_view
    start_importing:
      model:
        import_action_view: 
          keyword: import_progress_view
        import_progress: 25
        stage:
          text:
            literal: "Creating a new import"
      cmds:
        - effect: ws
          encoder: import_create_request
        - effect: ui
          encoder: import_layout_view
    import_created:
      model:
        import:
          key: import
          in:
            key: data
        import_progress: 50
        stage:
          text:
            literal: "Requesting permission to upload data"
      cmds:
        - effect: ws
          encoder: import_token_request 
        - effect: ui
          encoder: import_layout_view
    import_token:
      model:
        token:
          key: token
          in: data
        import_progress: 75
        stage:
          literal: "Uploading"
      cmds:
        - effect: file
          encoder: import_upload_request
  encoders:
    import_create_request:
      object:
        effect:
          keyword: ws
        action:
          keyword: create_import
    import_token_request:
      object:
        effect:
          keyword: ws
        action:
          keyword: token
        subject:
          key: id
          in: import
        intent:
          keyword: attach
        type:
          keyword: import
    import_upload_request:
      object:
        effect: 
          keyword: http
        method:
          keyword: post
        headers:
          object:
            content-type: 
              literal: "application/xml"
            cmauth:
              key: token
        body:
          file: 
            key: files
    select_file:
      view:
        tag: div
        children:
          - tag: label
            attrs:
              class: "c-hand label label-primary btn btn-label"
              for:
                key: id
            children:
              - text:
                  key: title
          - tag: input
            attrs:
              type: "file"
              id: 
                key: id
              onchange:
                key: change
              class: "d-hide"
    import_selectfile_view:
      view:
        tag: div
        attrs:
          key: "import_select_file"
        children:
          - view: label
            params:
              object:
                title:
                  text:
                    literal: "Please select a Wordpress file to import"
          - view: select_file
            params:
              object:
                change: 
                  keyword: import_file_selected 
                title: 
                  text:
                    literal: "Choose a file"
                id: 
                  text:
                    literal: "upload"
    import_main_sections_view:
      view:
        tag: div
        attrs:
          key: "import_sections"
        children:
          - view:
              key: action_view
              in: data
            params:
              object:
                data: 
                  key: data
    import_main_view:
      view:
        view: main
        params:
          object:
            title:
              text:
                literal: "Import"
            view:
              keyword: import_main_sections_view
            data:
              key: data
    import_layout_view: 
      view:
        view: layout
        params:
          object:
            message:
              key: message
            content_view:
              keyword: import_main_view
            contents:
              object:
                action_view: 
                  key: import_action_view
                files:
                  key: files
                progress:
                  key: import_progress
                stage:
                  key: stage
            sidebar:
              keyword: weekonekt_admin_sidebar
    import_upload_summary_view:
      view:
        tag: div
        attrs:
          key: "import_summary"
        children:
          - view: label
            params:
              object:
                title:
                  text:
                    literal: "All set up to start importing"
          - view: import_selected_files_view
            params:
              object:
                files:
                  key: files
                  in: data
          - view: button
            params:
              object:
                click: 
                  keyword: start_importing
                title: 
                  text:
                    literal: "Start importing"
    import_progress_view:
      view:
        tag: div
        attrs:
          key: "import_progress"
        children:
          - tag: span
            children:
              - text:
                  key: stage
                  in: data
          - view: progress
            params:
              object:
                value: 
                  text:
                    key: progress
                    in: data
                max:
                  text:
                    number: 100
          - view: button
            params:
              object:
                click: 
                  keyword: cancel_import
                title: 
                  text:
                    literal: "Cancel import"
    import_selected_files_view:
      view:
        tag: div
        attrs:
          class: "my-2"
        children:
          loop:
            key: files
          with: import_selected_file_view
    import_selected_file_view:
      view:
        tag: strong
        children:
          - text:
              key: name
              in: item
  decoders:
    show_import_ui:
      object:
        effect:
          keyword: ui
        event:
          text:
            literal: "import"
    start_importing:
      object:
        effect:
          keyword: ui
        event:
          text:
            keyword: start_importing
    import_file_selected:
      object:
        effect:
          keyword: ui
        event:
          keyword: import_file_selected
        value:
          list:
            file: any
    import_created:
      object:
        effect:
          keyword: ws
        data:
          object:
            import:
              object:
                status:
                  text:
                    literal: "created"
                id:
                  any: text
                date:
                  any: number
    import_token:
      object:
        effect:
          keyword: ws
        data:
          object:
            token:
              any: text
