version: 1.0
type: task
name: certs_domain_deploy
spec:
  - git:
      credentials:
        key: github
        in: settings
      clone: 
        repo: "github.com/netscale-technologies/certs.git"
        dir: 
          format:
            pattern: "/tmp/certs/~s"
            params:
              - key: settings
                in: params
  - kube:
      kind: secret
      name: "nc-cert"
      namespace: "nc"
      state: 
        keyword: present
      server:
        key: kubernetes
        in: settings
      props:
        object:
          key:
            file:
              at:
                format:
                  pattern: "/tmp/certs/~s/domains/~s.key"
                  params:
                    - key: settings
                      in: params
                    - key: domain
                      in: params
          cert: 
            file:
              at:
                format:
                  pattern: "/tmp/certs/~s/domains/~s.crt"
                  params:
                    - key: settings
                      in: params
                    - key: domain
                      in: params
  - kube:
      kind: pod
      namespace: "nc"
      state:
        keyword: absent
      server:
        key: kubernetes
        in: settings
      props:
        object:
          labels:
            object:
              app: coturn
  - slack:
      settings:
        key: slack
        in: params
      severity:
        keyword: "success"
      subject:
        text: "SSL certificates deployed"
      body:
        format:
          pattern: "New SSL certificates have been deployed to ~s"
          params:
            - key: settings
              in: params
