version: 1.0
type: task
name: deploy_announce 
spec:
  - slack:
      settings:
        key: slack
        in: params
      severity:
        keyword: "success"
      subject:
        text: "Docker image deployed"
      body:
        format:
          pattern: "Docker image ~s is now deployed in ~s"
          params:
            - text:
                format:
                  pattern: "~s:~s"
                  params:
                    - key: repo
                      in: params
                    - key: tag
                      in: params
            - key: settings
              in: params
