version: 1.0
type: task
name: docker_announce
spec:
  - slack:
      settings:
        key: slack
        in: params
      severity:
        keyword: "success"
      subject:
        text: "Docker image ready"
      body:
        format:
          pattern: "Docker image ~s:~s is now ready"
          params:
            - key: repo
              in: params
            - key: tag
              in: params
