version: 1.0
type: task
name: github_announce
spec:
  - slack:
      settings:
        key: slack
        in: params
      severity:
        keyword: "success"
      subject:
        text: "Github code pushed"
      body:
        text: "Github code pushed"
