version: 1.0
type: task
name: netcomp_release_build
spec:
  - git:
      credentials:
        key: github
        in: settings
      tag: 
        repo: "github.com/kalta/netcomp.git"
        clone: false
        dir: 
          format: 
            pattern: "/tmp/~s"
            params:
              - key: name
                in: params
        prefix: 
          format:
            pattern: "~s-v"
            params:
              - key: name
                in: params
        increment: minor 
      as: tag
  - docker:
      credentials:
        key: docker
        in: settings
      build:
        dir:
          format:
            pattern: "/tmp/~s"
            params:
              - key: name
                in: params
        repo: "netcomposer/netcomp"
        tag:
          key: tag
          in: context
