version: 1.0
type: task
name: nimg_build
spec:
  - git:
      credentials:
        key: github
        in: settings
      clone: 
        repo: "github.com/netscale-technologies/nimg.git"
        dir: "/tmp/nimg"
  - docker:
      credentials:
        key: docker
        in: settings
      build:
        dir: "/tmp/nimg"
        repo: "netcomposer/nimg"
        tag: "latest"

