version: 1.0
type: task
name: nimg_release
spec:
  - git:
      credentials:
        key: github
        in: settings
      tag: 
        repo: "github.com/netscale-technologies/nimg.git"
        dir: "/tmp/nimg"
        clone: true
        prefix: "v"
        increment:
          key: increment
          in: params
      as: tag
  - docker:
      credentials:
        key: docker
        in: settings
      build:
        dir: "/tmp/nimg"
        repo: "netcomposer/nimg"
        tag:
          key: tag
          in: context
