version: 1.0
type: task
name: pet_proxy_release
spec:
  - git:
      credentials:
        key: github
        in: settings
      tag: 
        repo: "github.com/netscale-technologies/dkv-pet-proxy.git"
        branch: master
        clone: true
        dir: "/tmp/dkv-pet-proxy"
        prefix: "v"
        increment:
          key: increment
          in: params
      as: tag
  - docker:
      credentials:
        key: docker
        in: settings
      build:
        dir: "/tmp/dkv-pet-proxy"
        repo: "netcomposer/dkv-pet-proxy"
        tag:
          key: tag
          in: context
