version: 1.0
type: task
name: pet_proxy_deploy 
spec:
  - kube:
      kind: deployment
      name:
        key: name
        in: params
      state: 
        keyword: present
      server:
        key: kubernetes
        in: settings
      namespace: nc
      props:
        object:
          retries: 120
          labels:
            object:
              app:
                key: name
                in: params
          replicas: 1
          spec:
            object:
              imagePullSecrets:
                list:
                  - name: 
                      text: docker
              containers:
                list:
                  - object:
                      name:
                        key: name
                        in: params
                      imagePullPolicy: 
                        text: "Always"
                      image:
                        text:
                          format:
                            pattern: "~s:~s"
                            params:
                              - key: repo
                                in: params
                              - key: tag
                                in: params
                      readinessProbe:
                        httpGet:
                          path: /
                          port: 8080
                        initialDelaySeconds: 10
                        timeoutSeconds: 1
                        periodSeconds: 15
                      env:
                        list:
                          - name: DKV_PET_HOST
                            value: "dkv-09-shp"
                          - name: DKV_PET_PORT
                            value: "9003"
                          - name: DKV_PET_PATH
                            value: "/_api"
                          - name: DKV_PET_SCHEME
                            value: "http"
                          - name: DKV_OAUTH_HOST
                            value:
                              key: host
                              in:
                                key: oauth
                                in:
                                  key: dkv
                                  in: settings
                          - name: DKV_OAUTH_PORT
                            value:
                              text:
                                key: port
                                in:
                                  key: oauth
                                  in:
                                    key: dkv
                                    in: settings
                          - name: DKV_OAUTH_PATH
                            value:
                              key: path
                              in:
                                key: oauth
                                in:
                                  key: dkv
                                  in: settings
                          - name: DKV_OAUTH_SCHEME
                            value:
                              key: transport
                              in:
                                key: oauth
                                in:
                                  key: dkv
                                  in: settings
                          - name: DKV_OAUTH_CLIENT_ID
                            value:
                              key: client_id
                              in:
                                key: oauth
                                in:
                                  key: dkv
                                  in: settings
                      ports:
                        list:
                          - object:
                              containerPort: 8080 
                              name:
                                text: "http"
                              protocol:
                                text: "TCP"
  - wait:
      condition:
        eq:
          - number: 200
          - key: status
            in:
              http:
                method: get
                url:
                  host:
                    key: host
                    in: settings
                  port:
                    key: port 
                    in:
                      key: pet
                      in:
                        key: dkv
                        in: settings
                  path:
                    key: path
                    in:
                      key: pet
                      in:
                        key: dkv
                        in: settings
                  transport:
                    key: transport
                    in:
                      key: pet
                      in:
                        key: dkv
                        in: settings

      sleep: 1000
      retries: 60
  - http:
      method: post 
      url:
        object:
          url:
            key: default
            in:
              key: webhooks
              in: settings
      headers:
        object:
          x-cm-event:
            text: "deploy-summary"
      body:
        object:
          settings:
            key: settings
            in: params
          repo:
            key: repo
            in: params
          tag:
            key: tag
            in: params
