version: 1.0
type: task
name: recent_backups 
spec:
  - iterate:
      sequence:
        from: 0
        to:
          key: days
          in: params
    as: day
    with:
      pipe:
        - calendar:
            days:
              ago:
                key: day
        - format:
            pattern: "~4..0B~2..0B~2..0B"
            params:
              - key: year
                in: date
              - key: month
                in: date
              - key: day
                in: date
      as: date
  - iterate:
      key: last
      in: context
    as: date
    with:

  - dump: context
