version: 1.0
type: task
name: test 
spec:
  - attempt:
      error:
        keyword: simulated_error
    onerror:
      - slack:
          settings:
            key: slack
            in: params
          severity:
            keyword: "danger"
          subject:
            text: "Build failed"
          body:
            format:
              pattern: "Failed to compile ~s"
              params:
                - key: name
                  in: params
      - error:
          object:
            reason:
              keyword: build_failed
            name:
              - key: name
                in: params
        
