version: 1.0
type: task
name: webclient_deploy
spec:
  - kube:
      deployment:
        object:
          namespace: "nc"
          name: 
            key: name
            in: params
          labels:
            object:
              app:
                key: name
                in: params
          replicas: 1
          spec:
            object:
              imagePullSecrets:
                list:
                  - name: 
                      text: docker
              volumes:
                list:
                  - name: config
                    configMap:
                      name:
                        key: name
                        in: params
              containers:
                list:
                  - object:
                      name:
                        key: name
                        in: params
                      image:
                        text:
                          format:
                            pattern: "~s:~s"
                            params:
                              - key: repo
                                in: params
                              - key: tag
                                in: params
                      volumeMounts:
                        list:
                          - object:
                              name: "config"
                              mountPath: "/static/js/config/config.js"
                              subPath: "config.js"
                              readOnly:
                                keyword: true
                      ports:
                        list:
                          - object:
                              containerPort: 3000
                              name:
                                text: "http"
                              protocol:
                                text: "TCP"
  - slack:
      settings:
        key: slack
        in: params
      severity:
        keyword: "success"
      subject:
        text: "Docker image deployed"
      body:
        format:
          pattern: "Docker image ~s is now deployed in ~s"
          params:
            - text:
                format:
                  pattern: "~s:~s"
                  params:
                    - key: repo
                      in: params
                    - key: tag
                      in: params
            - key: settings
              in: params
