{application,cmcss,
             [{description,"An OTP library"},
              {vsn,"0.1.0"},
              {registered,[]},
              {applications,[kernel,stdlib,cmkit]},
              {env,[]},
              {modules,[cmcss]},
              {maintainers,[]},
              {licenses,["Apache 2.0"]},
              {links,[]}]}.
