{application,cmweb,
             [{description,"An OTP application"},
              {vsn,"0.1.0"},
              {registered,[]},
              {mod,{cmweb_app,[]}},
              {applications,[kernel,stdlib,ranch,cowboy,cmkit,cmconfig]},
              {env,[]},
              {modules,[cmweb_app,cmweb_http,cmweb_http_metrics,cmweb_sup,
                        cmweb_ws]},
              {maintainers,[]},
              {licenses,["Apache 2.0"]},
              {links,[]}]}.
