version: 1.0
type: app
category: api
name: admin_api
spec:
  debug: true 
  modules:
    - ping
    - db_reset
    - common_api
    - login_api
    - register_api
    - apps
    - nodes_api
    - ports_api
    - buckets_api
    - modules_api
    - app_info_api
    - app_config_api
    - module_api
    - projects_api
    - issues_api
    - milestones_api
    - tests_api
  config:
    role:
      keyword: admin
    sessions:
      keyword: many
    key:
      text:
        literal: "87fb5ce6-d847-494b-ac35-a1a37186c276"
    timeout:
      number: 30
    databases:
      list:
        - keyword: tracker
        - keyword: users 
