version: 1.0
type: app
category: api
name: weekonekt_admin_api
spec:
  debug: true 
  modules:
    - ping
    - login_api
    - register_api
    - db_reset
  config:
    role:
      keyword: weekonekt_admin
    key:
      text: 
        literal: "2fc0b674-38f1-40b1-845b-53ec2ffc8a42"
