type: module
name: app 
spec:
  decoders:
    app:
      object:
        headers:
          app:
            in:
              config:
                key: apps
    missing:
      one_of:
        - object:
            headers:
              without_keys:
                - app
        - object:
            headers:
              app:
                not:
                  in:
                    config:
                      key: apps
  update:
    app:
      model:
        app:
          key: headers.app
        bucket:
          keyword:
            config:
              key: db
              in:
                key:  headers.app
    missing:
      cmds:
        - effect: terminate
          encoder: forbidden
