version: 1.0
type: module
category: ui
name: settings_ui
spec:
  init:
    model:
      settings:
        list: []
  decoders:
    show_settings:
      object:
        effect:
          keyword: ui
        event:
          text:
            literal: "settings"
    settings:
      object:
        effect:
          keyword: ws
        data:
          object:
            settings:
              any: list
  update:
    settings:
      model:
        settings:
          key: settings
          in: 
            key: data
      cmds:
        - effect: ui
          encoder: settings_view
    show_settings:
      cmds:
        - effect: ui
          encoder: settings_view
        - effect: ws
          encoder: settings
  encoders:
    settings:
      object: 
        action:
          keyword: settings 
    settings_item_view:
      view:
        view: accordion_view
        params:
          object:
            id:
              key: name
              in: item
            header:
              object:
                view:
                  keyword: text_view
                data:
                  object:
                    data:
                      key: name
                      in: item
            body:
              object:
                view:
                  keyword: json_view
                data:
                  object:
                    source:
                      key: spec
                      in: item
    settings_main_view:
      view:
        tag: div
        attrs:
          class: "card"
        children:
          - tag: h1
            attrs:
              class: "content-view"
            children:
              - text:
                  literal: "Settings"
          - tag: div
            children:
              loop:
                key: data
              with: settings_item_view
    settings_view: 
      view:
        view: layout
        params:
          object:
            theme:
              key: theme
            message:
              key: message
            content_view:
              keyword: settings_main_view
            contents:
              key: settings
            sidebar:
              keyword: admin_sidebar
