version: 1.0
type: template
name: netcomp_rebar_config 
spec:
  contents: |- 
    %%-*- mode: erlang -*-
    {cover_enabled, true}.

    {erl_opts, [
      debug_info, warnings_as_errors, {parse_transform, lager_transform}
    ]}.

    {overrides, [
             {del, [{erl_opts, [warnings_as_errors]}]}]}.

    {deps, [
      {nkservice, {git, "https://github.com/netcomposer/nkservice", {branch, "v09"}}},
      {nkdomain, {git, "https://github.com/netcomposer/nkdomain", {branch, "v09"}}},
      {nkchat, {git, "https://github.com/netcomposer/nkchat", {branch, "v09"}}}, 
      {nkswarm, {git, "https://github.com/pedro-gutierrez/nkswarm", {tag, "v1.0.2"}}},
      {nkstats, {git, "https://github.com/pedro-gutierrez/nkstats", {tag, "v1.1.1"}}},
      {nkkafka, {git, "https://github.com/netcomposer/nkkafka", {branch, "v09"}}},
      {nkcassandra, {git, "https://github.com/netcomposer/nkcassandra", {branch, "v09"}}},
    
    {% for d in private_deps %}  {% verbatim %}{{% endverbatim %}{{ d.name }}, {git, "https://{{ d.auth }}@github.com/{{ d.repo }}", {branch, "{{ d.branch }}"}}},
    {% endfor %}
      {nktranscoder, {git, "https://github.com/netcomposer/nktranscoder", {branch, "master"}}},
      {nkimage, {git, "https://github.com/netcomposer/nkimage", {branch, "master"}}},
      {media_converter, {git, "https://github.com/pedro-gutierrez/media-converter", {branch, "master"}}}]}.

    {profiles, [
      {prod, [
        {relx, [
          {dev_mode, false},
          {include_erts, false}
        ]}
      ]}
    ]}.
  
    {relx, [
      {release, {netcomp, "0.0.1"}, [
        netcomp
      ]},
    
      {dev_mode, true},
      {include_erts, false},
      {generate_start_script, true},
      {extended_start_script, true},
      {overlay_vars, "config/vars.config"},
      {overlay, [
        {mkdir, "etc"},
        {mkdir, "share/schema"},
        {mkdir, "data"},
        {mkdir, "log"}]}]}.
