apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  creationTimestamp: null
  name: release
spec:
  pipelineSpec:
    tasks:
    - name: from-build-pack
      resources: {}
      taskSpec:
        metadata: {}
        stepTemplate:
          env:
          - name: APP_NAME
            value: cmnode          
          - name: SONAR_TOKEN
            value: sqp_b9d4b8a7b2f635cc6c93f35260456819dc0f9edb
          - name: SONAR_PROJECT_KEY
            value: jaraxasoftware_cmnode_AYNU9JJhcCNr9YCAVsIE               
          - name: SONAR_URL
            value: https://sonarqube-jx3.develop.jaraxa.systems
          - name: SONAR_EXCLUSIONS
            value: "**/*.js,**/*.css,**/*.html,**/nkpdf/samples/*"
          image: uses:jaraxasoftware/jaraxa-pipeline-catalog/tasks/erlang-rebar/release.yaml@versionStream
          name: ""
          resources:
            # override limits for all containers here
            limits: {}
          workingDir: /workspace/source
        steps:
        - image: uses:jaraxasoftware/jaraxa-pipeline-catalog/tasks/git-clone/git-clone.yaml@versionStream
          name: ""
          resources: {}
        - name: next-version
          resources: {} 
        - name: jx-variables
          resources: {}
        - name: build-erlang-develop
          resources: {}
        - name: sonar-code-analisys
          resources: {}
        - name: check-registry
          resources: {}
        - name: build-container-build
          resources: {}
        - name: promote-changelog
          resources: {}
  podTemplate: {}
  serviceAccountName: tekton-bot
  timeout: 12h0m0s
status: {}
